// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44GQF8gU3uFWrka76IxJmJ6fs6vnSmFk',
    appId: '1:25275793757:web:ba17c45b91b40bcd6d28b4',
    messagingSenderId: '25275793757',
    projectId: 'sachinapp-d29f1',
    authDomain: 'sachinapp-d29f1.firebaseapp.com',
    storageBucket: 'sachinapp-d29f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEDJuJBTeCkeNwikWoYwYAazekAc_MCKY',
    appId: '1:25275793757:android:d4666dec4afa39d66d28b4',
    messagingSenderId: '25275793757',
    projectId: 'sachinapp-d29f1',
    storageBucket: 'sachinapp-d29f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstxJS4WGZ33Oa2t6JdazuYBkiot4g96Y',
    appId: '1:25275793757:ios:db99aa0377e713976d28b4',
    messagingSenderId: '25275793757',
    projectId: 'sachinapp-d29f1',
    storageBucket: 'sachinapp-d29f1.appspot.com',
    iosClientId: '25275793757-l72kfbef4riqa2jlgltelnd0e7p9a5ue.apps.googleusercontent.com',
    iosBundleId: 'com.sachinapp.blackout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstxJS4WGZ33Oa2t6JdazuYBkiot4g96Y',
    appId: '1:25275793757:ios:db99aa0377e713976d28b4',
    messagingSenderId: '25275793757',
    projectId: 'sachinapp-d29f1',
    storageBucket: 'sachinapp-d29f1.appspot.com',
    iosClientId: '25275793757-l72kfbef4riqa2jlgltelnd0e7p9a5ue.apps.googleusercontent.com',
    iosBundleId: 'com.sachinapp.blackout',
  );
}
